service: my-express-application

custom:
  tableName: 'calculations-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["CalculationsDynamoDBTable", "Arn" ] }
    - Effect: Allow
      Resource: "*"
      Action:
        - "sns:*"
  environment:
    CALCULATIONS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  store:
    handler: index.store
    events:
      - sns: 'yotam-store-sns'

resources:
  Resources:
    CalculationsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: calcId
            AttributeType: S
        KeySchema:
          -
            AttributeName: calcId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
